  
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        docker version
        # 登录阿里云镜像仓库
        docker login --username=bysx111 --password=bysx222 github.com/bysx111/bysx321
        # 使用Dockerfile构建镜像
        docker build . --file Dockerfile --tag hanzp
        # 推送镜像到镜像仓库
        docker push hanzp
